# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\ifsw-ffetzer\Documents\GitHub\PyPlotter\diag.ui'
#
# Created: Mon Apr 14 15:48:25 2014
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(1121, 785)
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 731, 421))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.lineEdit = QtGui.QLineEdit(self.groupBox)
        self.lineEdit.setGeometry(QtCore.QRect(250, 40, 201, 20))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.PlotSets_PB = QtGui.QPushButton(self.groupBox)
        self.PlotSets_PB.setGeometry(QtCore.QRect(170, 280, 75, 23))
        self.PlotSets_PB.setObjectName(_fromUtf8("PlotSets_PB"))
        self.ReadSets_PB = QtGui.QPushButton(self.groupBox)
        self.ReadSets_PB.setGeometry(QtCore.QRect(20, 120, 101, 23))
        self.ReadSets_PB.setObjectName(_fromUtf8("ReadSets_PB"))
        self.PlotColumn_PB = QtGui.QPushButton(self.groupBox)
        self.PlotColumn_PB.setGeometry(QtCore.QRect(500, 280, 75, 23))
        self.PlotColumn_PB.setObjectName(_fromUtf8("PlotColumn_PB"))
        self.ReadLabBook = QtGui.QPushButton(self.groupBox)
        self.ReadLabBook.setGeometry(QtCore.QRect(10, 150, 121, 23))
        self.ReadLabBook.setObjectName(_fromUtf8("ReadLabBook"))
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(160, 80, 46, 13))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(480, 80, 61, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(300, 80, 46, 13))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.ShowFile_PB = QtGui.QPushButton(self.groupBox)
        self.ShowFile_PB.setGeometry(QtCore.QRect(30, 180, 75, 23))
        self.ShowFile_PB.setObjectName(_fromUtf8("ShowFile_PB"))
        self.SetScroll = QtGui.QListWidget(self.groupBox)
        self.SetScroll.setGeometry(QtCore.QRect(140, 100, 131, 171))
        self.SetScroll.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.SetScroll.setObjectName(_fromUtf8("SetScroll"))
        self.FileScroll = QtGui.QListWidget(self.groupBox)
        self.FileScroll.setGeometry(QtCore.QRect(280, 100, 181, 171))
        self.FileScroll.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.FileScroll.setObjectName(_fromUtf8("FileScroll"))
        self.ColumnScroll = QtGui.QListWidget(self.groupBox)
        self.ColumnScroll.setGeometry(QtCore.QRect(470, 100, 231, 171))
        self.ColumnScroll.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.ColumnScroll.setObjectName(_fromUtf8("ColumnScroll"))
        self.PlotFile_PB = QtGui.QPushButton(self.groupBox)
        self.PlotFile_PB.setGeometry(QtCore.QRect(300, 280, 75, 23))
        self.PlotFile_PB.setObjectName(_fromUtf8("PlotFile_PB"))
        self.ColsOfInterestEdit = QtGui.QLineEdit(self.groupBox)
        self.ColsOfInterestEdit.setGeometry(QtCore.QRect(160, 350, 291, 20))
        self.ColsOfInterestEdit.setObjectName(_fromUtf8("ColsOfInterestEdit"))
        self.label_10 = QtGui.QLabel(self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(30, 350, 121, 20))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.AverageSets = QtGui.QCheckBox(self.groupBox)
        self.AverageSets.setGeometry(QtCore.QRect(160, 310, 131, 21))
        self.AverageSets.setChecked(False)
        self.AverageSets.setObjectName(_fromUtf8("AverageSets"))
        self.Clear_PB = QtGui.QPushButton(self.groupBox)
        self.Clear_PB.setGeometry(QtCore.QRect(20, 210, 111, 31))
        self.Clear_PB.setObjectName(_fromUtf8("Clear_PB"))
        self.WorkingD_label = QtGui.QLabel(self.groupBox)
        self.WorkingD_label.setGeometry(QtCore.QRect(130, 10, 461, 20))
        self.WorkingD_label.setObjectName(_fromUtf8("WorkingD_label"))
        self.Select_PB = QtGui.QPushButton(self.groupBox)
        self.Select_PB.setGeometry(QtCore.QRect(470, 40, 93, 28))
        self.Select_PB.setObjectName(_fromUtf8("Select_PB"))
        self.Pyro_PB = QtGui.QPushButton(self.groupBox)
        self.Pyro_PB.setGeometry(QtCore.QRect(120, 40, 101, 28))
        self.Pyro_PB.setObjectName(_fromUtf8("Pyro_PB"))
        self.groupBox_2 = QtGui.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 430, 731, 251))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.FFT_PB = QtGui.QPushButton(self.groupBox_2)
        self.FFT_PB.setGeometry(QtCore.QRect(450, 80, 75, 23))
        self.FFT_PB.setObjectName(_fromUtf8("FFT_PB"))
        self.LP_slider = QtGui.QSlider(self.groupBox_2)
        self.LP_slider.setGeometry(QtCore.QRect(40, 80, 111, 19))
        self.LP_slider.setMaximum(10000)
        self.LP_slider.setOrientation(QtCore.Qt.Horizontal)
        self.LP_slider.setObjectName(_fromUtf8("LP_slider"))
        self.HP_slider = QtGui.QSlider(self.groupBox_2)
        self.HP_slider.setGeometry(QtCore.QRect(230, 80, 151, 19))
        self.HP_slider.setMaximum(10000)
        self.HP_slider.setOrientation(QtCore.Qt.Horizontal)
        self.HP_slider.setObjectName(_fromUtf8("HP_slider"))
        self.label = QtGui.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(75, 100, 51, 20))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(290, 100, 61, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.MAV_slider = QtGui.QSlider(self.groupBox_2)
        self.MAV_slider.setGeometry(QtCore.QRect(140, 140, 160, 19))
        self.MAV_slider.setMaximum(1000)
        self.MAV_slider.setOrientation(QtCore.Qt.Horizontal)
        self.MAV_slider.setObjectName(_fromUtf8("MAV_slider"))
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(40, 140, 91, 20))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(480, 20, 91, 20))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.CurrentFigureEdit = QtGui.QLineEdit(self.groupBox_2)
        self.CurrentFigureEdit.setGeometry(QtCore.QRect(580, 20, 31, 20))
        self.CurrentFigureEdit.setObjectName(_fromUtf8("CurrentFigureEdit"))
        self.LPEdit = QtGui.QLineEdit(self.groupBox_2)
        self.LPEdit.setGeometry(QtCore.QRect(160, 80, 31, 20))
        self.LPEdit.setObjectName(_fromUtf8("LPEdit"))
        self.HPEdit = QtGui.QLineEdit(self.groupBox_2)
        self.HPEdit.setGeometry(QtCore.QRect(390, 80, 31, 20))
        self.HPEdit.setObjectName(_fromUtf8("HPEdit"))
        self.InActiveFigure = QtGui.QCheckBox(self.groupBox_2)
        self.InActiveFigure.setGeometry(QtCore.QRect(310, 20, 141, 17))
        self.InActiveFigure.setChecked(True)
        self.InActiveFigure.setObjectName(_fromUtf8("InActiveFigure"))
        self.MAVEdit = QtGui.QLineEdit(self.groupBox_2)
        self.MAVEdit.setGeometry(QtCore.QRect(310, 140, 31, 20))
        self.MAVEdit.setObjectName(_fromUtf8("MAVEdit"))
        self.SelectedRange = QtGui.QCheckBox(self.groupBox_2)
        self.SelectedRange.setGeometry(QtCore.QRect(120, 20, 121, 17))
        self.SelectedRange.setObjectName(_fromUtf8("SelectedRange"))
        self.Export_PB = QtGui.QPushButton(self.groupBox_2)
        self.Export_PB.setGeometry(QtCore.QRect(580, 210, 121, 23))
        self.Export_PB.setObjectName(_fromUtf8("Export_PB"))
        self.SubtractMean_PB = QtGui.QCheckBox(self.groupBox_2)
        self.SubtractMean_PB.setGeometry(QtCore.QRect(540, 80, 131, 17))
        self.SubtractMean_PB.setObjectName(_fromUtf8("SubtractMean_PB"))
        self.MVAREdit = QtGui.QLineEdit(self.groupBox_2)
        self.MVAREdit.setGeometry(QtCore.QRect(310, 180, 31, 20))
        self.MVAREdit.setObjectName(_fromUtf8("MVAREdit"))
        self.MMMINEdit = QtGui.QLineEdit(self.groupBox_2)
        self.MMMINEdit.setGeometry(QtCore.QRect(310, 210, 31, 20))
        self.MMMINEdit.setObjectName(_fromUtf8("MMMINEdit"))
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(240, 180, 46, 13))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_11 = QtGui.QLabel(self.groupBox_2)
        self.label_11.setGeometry(QtCore.QRect(240, 210, 46, 13))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.Corr_PB = QtGui.QPushButton(self.groupBox_2)
        self.Corr_PB.setGeometry(QtCore.QRect(450, 120, 75, 23))
        self.Corr_PB.setObjectName(_fromUtf8("Corr_PB"))
        self.textBrowser = QtGui.QTextBrowser(Dialog)
        self.textBrowser.setGeometry(QtCore.QRect(750, 20, 361, 171))
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        self.label_9 = QtGui.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(770, 210, 46, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.HistoryEdit = QtGui.QPlainTextEdit(Dialog)
        self.HistoryEdit.setGeometry(QtCore.QRect(770, 230, 104, 71))
        self.HistoryEdit.setObjectName(_fromUtf8("HistoryEdit"))

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.groupBox.setTitle(_translate("Dialog", "Read Data", None))
        self.lineEdit.setText(_translate("Dialog", "testdata/laborbuch.txt", None))
        self.PlotSets_PB.setText(_translate("Dialog", "Plot Sets", None))
        self.ReadSets_PB.setText(_translate("Dialog", "Read Set", None))
        self.PlotColumn_PB.setText(_translate("Dialog", "Plot Column", None))
        self.ReadLabBook.setText(_translate("Dialog", "Read from LabBook", None))
        self.label_6.setText(_translate("Dialog", "Sets", None))
        self.label_7.setText(_translate("Dialog", "Columns", None))
        self.label_8.setText(_translate("Dialog", "Files", None))
        self.ShowFile_PB.setText(_translate("Dialog", "Show File", None))
        self.PlotFile_PB.setText(_translate("Dialog", "Plot File", None))
        self.ColsOfInterestEdit.setText(_translate("Dialog", "Zeit, ATemp, STemp, CtrlOut, CtrlNr", None))
        self.label_10.setText(_translate("Dialog", "Columns of interest", None))
        self.AverageSets.setText(_translate("Dialog", "Average over Set", None))
        self.Clear_PB.setText(_translate("Dialog", "Clear All", None))
        self.WorkingD_label.setText(_translate("Dialog", "TextLabel", None))
        self.Select_PB.setText(_translate("Dialog", "Select File", None))
        self.Pyro_PB.setText(_translate("Dialog", "Read Pyro", None))
        self.groupBox_2.setTitle(_translate("Dialog", "Eval Data", None))
        self.FFT_PB.setText(_translate("Dialog", "FFT", None))
        self.label.setText(_translate("Dialog", "Low Pass", None))
        self.label_3.setText(_translate("Dialog", "High Pass", None))
        self.label_5.setText(_translate("Dialog", "Moving Avg.", None))
        self.label_2.setText(_translate("Dialog", "active Data Figure", None))
        self.CurrentFigureEdit.setText(_translate("Dialog", "0", None))
        self.InActiveFigure.setText(_translate("Dialog", "Apply in Current Figure", None))
        self.SelectedRange.setText(_translate("Dialog", "Use Selected range", None))
        self.Export_PB.setText(_translate("Dialog", "export Plotted Data", None))
        self.SubtractMean_PB.setText(_translate("Dialog", "subtract mean", None))
        self.label_4.setText(_translate("Dialog", "MVAR", None))
        self.label_11.setText(_translate("Dialog", "MMMIN", None))
        self.Corr_PB.setText(_translate("Dialog", "Corrrelate", None))
        self.label_9.setText(_translate("Dialog", "History", None))
        self.HistoryEdit.setPlainText(_translate("Dialog", "asAS", None))

